### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by jrslagle**
I went through and used my IDE's "optimize imports" feature on all classes. It removed all unused imports and sorted them alphabetically. It also exposed some bugs in Corn, Tomato, and Turnip (which I'll submit a fix for next). This did not reduce the amount of RAM used. (Apparently imports don't load data, they just help the compiler resolve class name abbreviations to their full path names.)

### CODE REVIEW

**Comment by jrslagle** [comment]
Ok, I have no idea how these added files keep creeping into different branches. I definitely did all my commits in their respective branches.

**Comment by jrslagle** [comment]
I think I know what happened. I created my clean-imports branch while still on the add-potato branch. Note to noobs, creating another branch FROM a feature branch will take that feature's commits with it. If you want your pull requests to have separate lines of commits, go back to master first.

**Comment by Master-Foo** [comment]
Having abandoned imports isn't really a big deal. It will slow down the first time a program is run the first time it is run but not enough to notice., but after the script is turned into bytecode, it will have no effect on the runtime itself.

I'm denying this pull request because there are files associated with one of your previous pull requests in it. You can clean it up and resubmit, or just leave it be. We'll do some housecleaning after MVP goals are met.

**Comment by jrslagle** [comment]
K. Now that you've merged the potato stuff and I've rebased, all should be well. *fingers crossed*

**Comment by jrslagle** [comment]
DAMMIT!

**Comment by Master-Foo** [comment]
You are going to hate me for this, but I just did a significant codebase refactor.

I don't know if these conflicts reported here were conflicts before I pushed or **because** I pushed and now there is a conflict.

But regardless of that, you are still submitting code unrelated to the orphan imports. For instance, source/entities/potato/animation_config/damaged_picked.py

If it weren't for the Frankencode, I'd fix the merge conficts myself. But now, you'll have to do it while you are getting rid of the stray files.

So, go back and delete those files and then resolve the reported conflicts. I'll merge. I swear!

**Pull request closed without merging**
