### PR TITLE
Make a Plant Abstract Class

### PR DESCRIPTION
**Pull request by fishscene**
Resolve https://github.com/Master-Foo/game/issues/51
Plants inherit from plant class.
Move shared code from tomato, corn, turnip, potato into Plant.

### CODE REVIEW

**Comment by jrslagle** [comment]
@fishscene, welcome back btw!

**Comment by fishscene** [comment]
Mis-clicked while moving around programs on my screen.

**Comment by fishscene** [comment]
Don't pull this. I got the PR ready, then noticed a few junk files, as well as a bug when running. While diagnosing, accidentally sent a PR request. I never did figure out how to fix my bug, so I'll let @techwulf have this one.

**Comment by Master-Foo** [comment]
OK

**Pull request closed without merging**
