### PR TITLE
Avatar.pickup logic

### PR DESCRIPTION
**Pull request by jrslagle**
I just ran into this while doing a code inspection. The changes work on my machine.

### CODE REVIEW

**Comment by Master-Foo** [comment]
The reason there is a `return False` when it seemingly should not ever be reachable is for the sake of sanity. If the logic in that function ever changes, there will always be a `False` value returned, regardless of what happens.

As for the condensation, that doesn't really work because `get_nearest_item()` doesn't always return something. For instance, if no items are in reach of the Avatar. That is why there is a second check to see if the avatar is holding something. Calling `get_nearest_item()` doesn't guarantee that something will be returned.

Granted, there should probably a `get_nearest_reachable_item()` for clarity that calls `get_nearest_item()` and does the "is reachable" logic inside. But the logic as-is, is sound.

Also, you've removed the `self.holding.on_pickup()` which sends a signal to the thing being picked up, that it is being picked up. We might not need this now, but imagine picking up a porcupine and the porcupine needs to be notified that it is being picked up so it can say to itself "OK, what do I do when I get picked up?" then, it gets angry or something.

I'm going to refuse this commit. However, I think it's a good idea to add `get_nearest_reachable_item()`. It's probably best to make an issue for these kinds of things before working on them, because usually there is a reason for "Unreachable Code". If we discuss the problem before you spend time on it, and the solution isn't necessary, it could save you time in the future.

**Comment by jrslagle** [comment]
@Master-Foo 
did you mean this? because the distance logic is now redundant

```
    def get_nearest_item(self):
        shortest_distance   = None
        item                = None
        for entity in self.parent.homestead.entities:
            distance = self.position.distance_to(entity.position)
            if distance < self.reach:
                if distance < shortest_distance or shortest_distance == None:
                    shortest_distance = distance
                    item = entity
        return item

    def get_nearest_reachable_item(self):
        item = self.get_nearest_item() # could return None if there are no entities in homestead
        if item != None:
            distance = self.position.distance_to(item.position)
            if distance < self.reach:
                return item
            else:
                return None
        else:
            return None
```

**Comment by Master-Foo** [comment]
That's a good start. But you can break it up better with something like this:

```python
def get_nearest_item():
    shortest_distance   = None
    item                      = None
    for entity in self.parent.homestead.entities:
            if distance < shortest_distance or shortest_distance == None:
                shortest_distance = distance
                item = entity
    return item

def get_nearest_reachable_item(self):
    item = self.get_nearest_item() # could return None if there are no entities in homestead
    if item != None:
        distance = self.position.distance_to(item.position)
        if distance < self.reach:
            return item
        else:
            return None
    else:
       return None
```

This way, `get_nearest_item()` has a valid use case in that you are trying to just find the nearest item, even if it's Meters away. reachable logic has been removed because reachable isn't a consideration of finding the nearest item.

However, `get_nearest_reachable_item()` is where the "reachable" logic is stored. Because it is concerened with narrowing down whether or not the "nearest item" is **also** reachable.

This way, we can still use `get_nearest_item()` for things like AI, which might just want to know where the nearest item is, so it can go there and pick it up.

**Comment by Master-Foo** [comment]
I think that it's OK to have

```python
distance = self.position.distance_to(entity.position)
```

be redundant, because you are going to need to calculate distance regardless, and that 1 line is already rendered down to it's simplest form anyway. There is a little overhead, but this is a I/O bound function. So, it's OK. If this were a CPU bound function, I'd go down the rabbit hole.

**Comment by jrslagle** [comment]
Oops, I missed `if distance < self.reach:` and forgot to remove it from get_nearest_item().

But why did you remove self from get_nearest_item(self)?

If I wanted to upgrade get_nearest_reachable_item to find the thing nearest my hands/scoop/hopper, would you accept passing the position of a grabber into get_nearest_item(position)?

**Comment by jrslagle** [comment]
K, I updated my code to a second draft. I also rearranged the pickup logic for my own sanity.

I noticed that the return True/False isn't being used anywhere. So are you just adding it for something like if(self.pickup()): adjust mass?

**Comment by Master-Foo** [comment]
It's not used currently, but there may be cases in the future where the pickup fails.

So, for instance, in the future, there will probably be a check that determines if the Avatar is strong enough to pick it up. So, picking up a rock would return True. Picking up a House would return False.

Likewise, maybe the thing you pick up has a kind of "Agility" modifier, like in D&D, picking up a pig returns True. Picking up a **greased** pig, Maybe it returns True, maybe False.

**Comment by jrslagle** [comment]
K. I think I've done everything I can think of.

-My IDE advises to never do "== None" and use "is None" or "is not None" instead. Don't know why.
-The True/False stuff makes sense to me at least.
-There isn't any dangling unreachable code.
-The if/else structure looks clean.
-There's a separate usable get_nearest_item method.

**Comment by jrslagle** [comment]
But.... the IDE God reads everything I write and sounds so smart....

I fixed those two things.

**Comment by jrslagle** [comment]
Whew.

**Pull request merged**
