### PR TITLE
Gravity

### PR DESCRIPTION
**Pull request by jrslagle**
Satisfies #49 

@Master-Foo I kind of did my own thing, so take a look.

### CODE REVIEW

**Comment by Master-Foo** [comment]
```bash
File "./demo/demo.py", line 10, in <module>
    game.on_loop()
  File "/home/masterfoo/git/game/source/abstract/app/controller/controller.py", line 38, in on_loop
    self.on_render()
  File "/home/masterfoo/git/game/source/abstract/app/view/view.py", line 8, in on_render
    self.universe.on_render()
  File "/home/masterfoo/git/game/source/systems/location/universe/view/view.py", line 9, in on_render
    self.galaxy.on_render()
  File "/home/masterfoo/git/game/source/systems/location/galaxy/view/view.py", line 9, in on_render
    self.solar_system.on_render()
  File "/home/masterfoo/git/game/source/systems/location/solar_system/view/view.py", line 9, in on_render
    self.planet.on_render()
  File "/home/masterfoo/git/game/source/systems/location/planet/view/view.py", line 15, in on_render
    self.homestead.on_render()
  File "/home/masterfoo/git/game/source/systems/location/homestead/view/view.py", line 11, in on_render
    entity.on_render()
  File "/home/masterfoo/git/game/source/abstract/entities/entity/view/view.py", line 30, in on_render
    self.set_animation()
  File "/home/masterfoo/git/game/source/abstract/entities/entity/view/view.py", line 25, in set_animation
    if abs(self.speed().length()) == 0:
AttributeError: Refinery instance has no attribute 'speed'
```

**Comment by jrslagle** [comment]
Oops. I forgot to test this one.

**Comment by Master-Foo** [comment]
Before you commit, here are some notes.

You make comments in the `translate()` function. Generally, it is a good indication that if you need comments in your code, you should break up that code into it's own function and name that function what the comment says.

Also, don't pass gravity into Planet's `__init__()` The gravity constant for any given planet should probably be dynamically calculated based on that planet's attributes. Radius is probably a good place to start with that.

**Comment by jrslagle** [comment]
Ok, I understand why we shouldn't initialize a planet with a starting gravity. That really can be derived from other parameters if we were to generate a random planet.

But what were your plans making the gravity of a planet dynamic? That's a little Earth shaking.

**Comment by jrslagle** [comment]
I currently have this bug on my gravity branch, and I'm not sure how self.get_planet() got to returning Homestead.

https://github.com/jrslagle/game/tree/gravity

  File "/home/jrslagle/Code/TerraCraft/game/source/abstract/entities/entity/model/model.py", line 93, in get_hectare
    hect = self.get_kilometer().hectares[0][0]
  File "/home/jrslagle/Code/TerraCraft/game/source/abstract/entities/entity/model/model.py", line 87, in get_kilometer
    kilo = self.get_planet().kilometers[0][0]
AttributeError: Homestead instance has no attribute 'kilometers'

**Comment by Master-Foo** [comment]
The plan is to procedurally generate everything as much as possible. So, if a planet has a radius of X it's gravitational "constant" will always be Y, so in that regard a planet's gravity shouldn't be dynamic, but a `Planet`'s gravity IS dynamic. We are using the same code to generate any number of planets. The variable we change should be `radius`, not the gravitational "constant".

As for those bugs, they aren't bugs so much as I haven't finished up the relational structure of various locations. For instance, some things are in some locations, like `Homestead`, Somethings, like Avatar are actually in `Planet`. I haven't solidified the logic to allow everything to find it's planet regardless of where it is at inside the data structure. I'll fix this tomorrow.

But basically, Everything should be able to call `self.planet()` and get the planet they are on regardless of where they are in the data structure.

It's complicated. If it doesn't work, put it aside for now. I'll fix it tomorrow.

**Pull request merged**
