### PR TITLE
Mined rock is moved to avatar before rendering

### LINKED ISSUE #62: Mined rock appears at top left corner for first frame.

### PR DESCRIPTION
**Pull request by jrslagle**
Satisfies #62

### CODE REVIEW

**Comment by Master-Foo** [comment]
This seems like kind of a hack implementation. I suspect that the better way to do it is in Human's Model's Mine function, when ore is created, immediately change `ore.position = self.position` because the ore is created by mining so the act of mining should determine where it is placed when created.

**Comment by Master-Foo** [comment]
I'll accept, but try to go back and see if my suggestion works, because I suspect this could cause confusion in the future if we don't solve the problem where it belongs.

**Comment by Master-Foo** [comment]
Yep, when I pick up an item this happens now

```bash
Traceback (most recent call last):
  File "./demo.py", line 8, in <module>
    game.on_loop()
  File "/home/masterfoo/git/game/source/abstract/app/app.py", line 46, in on_loop
    self.on_event()
  File "/home/masterfoo/git/game/source/abstract/app/app.py", line 29, in on_event
    keyboard.KEYBOARD.key_event(event)
  File "/home/masterfoo/git/game/source/interface/keyboard.py", line 6, in key_event
    self.on_key_down(event.key)
  File "/home/masterfoo/git/game/source/interface/keyboard.py", line 30, in on_key_down
    KEY_RETURN.down()
  File "/home/masterfoo/git/game/source/interface/keyboard.py", line 251, in down
    subscriber.on_keydown_return()
  File "/home/masterfoo/git/game/source/entities/human/avatar/controller/keyboard_events.py", line 69, in on_keydown_return
    self.pickup()
  File "/home/masterfoo/git/game/source/abstract/entities/human/model.py", line 47, in pickup
    self.holding.on_pickup()
TypeError: on_pickup() takes exactly 2 arguments (1 given)
```

This is because you added `parent` to on_pickup() which causes some problems. Avatar isn't the parent of the item being mined. Avatar is just holding an item and that item's parent is going to be a location, like planet, or Hectare, or Homestead. It's possible also that something has **no** parent.

I've never expalained this, so I don't blame you or anything. But adding new variables to controller events is generally a bad idea, the reason being is the above problem. That and generally speaking, controller variables shouldn't take inputs. They should just run when called and be able to get whatever information they need from the model.

**Comment by Master-Foo** [comment]
I fixed the above bug.

**Comment by Master-Foo** [comment]
Take a look at my [commit](https://github.com/Master-Foo/game/commit/e9e3e897f8253a2d9cff58417d0e4996b7e8d9e9) for a more canonical solution.

**Comment by jrslagle** [comment]
@Master-Foo 
Okay, that actually makes sense not to add inputs to the controller. I was thinking position setting should happen in self.pickup. Does it make a big difference?

**Comment by Master-Foo** [comment]
I did another commit after the one I pointed to that added a `dropped()` function into the model. Basically the avatar's controller calls the Avatar's model's `drop()` when the enter key is pressed. The Avatar's `drop()` calls the item's controller's `on_drop()` which calls the item's model's `dropped()` function. So, now, item modifies *itself* when it is notified that it has been dropped.

It's kind of confusing, but, basically, the moral of the story is, objects should do the modifications themselves when they are notified that something is happening. In this case, the Avatar is telling Rock that it is being dropped and the rock takes care of it's own logic.

**Pull request merged**
